'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const BASE_PRELOAD_PATH = 'vendor/carnival/electronapp/preload.js';
const PREPARED_PRELOAD_PATH = 'src/electronapp/preload.js';
const RUNTIME_PRELOAD_PATH = 'electronapp/preload.js';
const PREPARED_PRELOAD_MARKER = 'ETE_PREPARED_PRELOAD_V1';

// The vendor preload is the immutable baseline. This block is deliberately
// generated here so the ignored prepared file cannot depend on a developer's
// previous checkout. It only records diagnostic facts and never joins playback
// promises or changes a player command.
const DIAGNOSTICS_BLOCK = [
    '// ' + PREPARED_PRELOAD_MARKER + ': generated by tools/prepare-preload.cjs',
    "const diagnostics = require('./enhanced/diagnostics');",
    'window.__eteDiagnosticHash = diagnostics.hashPath;',
    'window.__eteBridgeReadiness = window.__eteBridgeReadiness || (function () {',
    "    var state = {version: 1, runId: null, startedAt: 0, ready: false, playing: false, readyAt: null, playingAt: null, readyBridge: null, playingBridge: null, events: []};",
    '    function beginRun(runId, startedAt) {',
    "        state.runId = String(runId || '');",
    '        state.startedAt = Number(startedAt) > 0 ? Number(startedAt) : Date.now();',
    '        state.ready = false;',
    '        state.playing = false;',
    '        state.readyAt = null;',
    '        state.playingAt = null;',
    '        state.readyBridge = null;',
    '        state.playingBridge = null;',
    '        state.events = [];',
    '        return state.snapshot();',
    '    }',
    '    function record(stage, bridge) {',
    "        var name = String(stage || '');",
    "        if (name !== 'ready' && name !== 'playing') return;",
    '        var at = Date.now();',
    '        if (state.events.length < 32) state.events.push({stage: name, at: at, runId: state.runId});',
    "        if (name === 'ready') { state.ready = true; state.readyAt = at; state.readyBridge = bridge || null; }",
    "        if (name === 'playing') { state.playing = true; state.playingAt = at; state.playingBridge = bridge || null; }",
    '    }',
    '    state.beginRun = beginRun;',
    '    state.record = record;',
    '    state.snapshot = function (bridge) {',
    '        return {version: state.version, runId: state.runId, startedAt: state.startedAt, ready: state.ready, playing: state.playing, readyAt: state.readyAt, playingAt: state.playingAt, eventCount: state.events.length, readyBridgeMatches: bridge ? state.readyBridge === bridge : null, playingBridgeMatches: bridge ? state.playingBridge === bridge : null};',
    '    };',
    '    return state;',
    '}());',
    'window.enhancedDiagnostics = function (bridge, stage) {',
    '    window.__eteBridgeReadiness.record(stage, bridge);',
    "    diagnostics.collect(bridge, window, stage).then(function (snapshot) {",
    "        ipcRenderer.send('enhanced-diagnostics', snapshot);",
    '    }).catch(function () { /* Optional diagnostics cannot fail playback. */ });',
    '};'
].join('\n');

function toCrlf(value) {
    return String(value).replace(/\r\n/g, '\n').replace(/\r/g, '\n').replace(/\n/g, '\r\n');
}

function sha256(value) {
    return crypto.createHash('sha256').update(value).digest('hex').toUpperCase();
}

function buildPreparedPreload(vendorText) {
    const source = toCrlf(vendorText).replace(/\r\n+$/, '');
    if (source.indexOf(PREPARED_PRELOAD_MARKER) >= 0) {
        throw new Error('Vendor preload already contains the prepared marker.');
    }
    if (!/window\.appdata = process\.env\.APPDATA;/.test(source)) {
        throw new Error('Vendor preload anchor is missing.');
    }
    return source + '\r\n\r\n' + toCrlf(DIAGNOSTICS_BLOCK) + '\r\n';
}

function prepare(root) {
    const repositoryRoot = path.resolve(root || path.join(__dirname, '..'));
    const vendorPath = path.join(repositoryRoot, BASE_PRELOAD_PATH);
    const preparedPath = path.join(repositoryRoot, PREPARED_PRELOAD_PATH);
    if (!fs.existsSync(vendorPath)) throw new Error('Vendor preload is missing: ' + BASE_PRELOAD_PATH);

    const vendorText = fs.readFileSync(vendorPath, 'utf8');
    const preparedText = buildPreparedPreload(vendorText);
    fs.mkdirSync(path.dirname(preparedPath), {recursive: true});
    let changed = true;
    try { changed = fs.readFileSync(preparedPath, 'utf8') !== preparedText; } catch (_) { }
    if (changed) fs.writeFileSync(preparedPath, preparedText, 'utf8');

    return {
        status: 'passed',
        basePath: BASE_PRELOAD_PATH,
        preparedPath: PREPARED_PRELOAD_PATH,
        runtimePath: RUNTIME_PRELOAD_PATH,
        baseSha256: sha256(Buffer.from(vendorText, 'utf8')),
        preparedSha256: sha256(Buffer.from(preparedText, 'utf8')),
        changed: changed
    };
}

if (require.main === module) {
    try {
        process.stdout.write(JSON.stringify(prepare(process.argv[2])) + '\n');
    } catch (error) {
        process.stderr.write(String(error && error.message || error) + '\n');
        process.exitCode = 1;
    }
}

module.exports = {
    BASE_PRELOAD_PATH,
    PREPARED_PRELOAD_MARKER,
    PREPARED_PRELOAD_PATH,
    RUNTIME_PRELOAD_PATH,
    DIAGNOSTICS_BLOCK,
    buildPreparedPreload,
    prepare,
    sha256
};
